#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 17 11:51:43 2018

@author: arthurmaroquenefroissart
"""
#%%
2 Exercises
#1. 3 points. Create a function named factorial that receives a number as a parameter and returns its factorial.
#2. 2 points. Create a function named maximum that receives a list of numbers as parameter and returns its maximum value.
 Use iteration.
##3. 2 points. Create a function named minimum that receives a list of numbers as parameter and returns its minimum value. Use iteration.
#4. 3 points. Write a function that returns a list containing all numbers between 0 and 1000 that are both multiples of 5 and 3

#%%

def factorial (num): 
    i = num
    factorial = 1 
    if num>= 0: 
        while i>= 1: 
            factorial = factorial * i 
            i = i-1
        print(factorial)
        
        
#%% 

list [4,6,7] non doit laisser entrer parametre 
maximum_number = None 

def maximum (list) : 
    for max in list : 
        if maximum_number is None or maximum_number > list:
            maximum_number = max 
        print (maximum_number)    
        
#%%

list = []   
def maximum (list):
    maxnumber=list[0]
    for i in range(0,len(list),1):
        if maxnumber < list[i]:
            maxnumber = list[i]
    print("the max is", maxnumber)
        
#%%
#%%

print("Type in a list of numbers, like the following: list=[1,2,3,4] and afterwoods use: maximum(list) to call the function")        
list=[]        
def maximum(list):
    maxnumber=list[0]
    for i in range(0,len(list),1):
        if maxnumber < list[i]:
            maxnumber = list[i]
    print("The maximum of the list is: ",maxnumber)
    
#%%
    
#3 points. Write a function that returns a list containing all
# numbers between 0 and 1000 that are both multiples of 5 and 3
 
 
finallist=[]
for i in range(1001):
    if i%3 ==0 or i%5 ==0:
        finallist.append(i)
        
print("The list of numbers from 0 to 1000 divisible by 3 or 5 are: ",finallist)

#%%
 
1. creer une list vide 
2. iteration dans la liste. pour chaque valeur dans la liste de range 1001
3. si i est divisible par 3 ou par 5 
4. ajouter dans la liste avec function append. 

 
 
 
 

    