#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 26 14:35:38 2018

@author: arthurmaroquenefroissart
"""
#%%
def linear(number, lst):
    for i in range(len(lst)):
        if number == lst[i]:
            return i
    
    return None   




#%%